version: "3"

services:
  nuxt:
    build: ./nuxt
    # command: >
    #   ash -c "
    #     npm i --silent &&
    #     npm run dev"
    env_file: ./.env
    volumes:
      - ./nuxt:/nuxt
      - npm_cache:/home/node/.npm
    ports:
      - 28080:3000
    stdin_open: true
    tty: true

volumes:
  npm_cache: